### ISSUE TITLE
Just two things!

### ISSUE THREAD

**Issue by navakelvin** [xpgo/obsidian-folder-note-plugin#1]
Your plugin works almost perfectly, it only takes two things.

1. It would be great if the _about_.md note takes the name of the same folder. I don't know how possible that would be for you.
2. Due to the collapsible behavior of folders when you want to go to the "folder note" it collapses. A solution for this could be for the folder to collapse with just the arrow and not with the name (that is, the entire label box).

Congrats, I hope you can get it. You've really come close to Obsidian Forum's "note hierarchy" request.

**Comment by xpgo** [comment]
Good suggestion!

1. It is very easy to set the note name same as folder name, I have set this as the default behavior, I also think this is better. Please see the Readme.
2. I don't know how to overwrite the collapse behavior based on the API, I'll leave this issue open, so someone may give me some help on this.

Thanks.

**Comment by xpgo** [comment]
> 1. It would be great if the _about_.md note takes the name of the same folder. I don't know how possible that would be for you.

I found that there would be potentially inconvenient to use the folder name as the note name. Whenever you change the folder name, then the note name has to be changed manually, it can not be done automatically right now due to the limitation of 
 current Obsidian's API.
