### ISSUE TITLE
folder_brief_live: use first found paragraph within notes as brief

### ISSUE THREAD

**Issue by ngirard** [xpgo/obsidian-folder-note-plugin#3]
In the same vein as #2, I'm following a pretty common convention with many of my notes, consisting in describing the gist of the note in its first paragraph.

Therefore, it would be much helpful to me, if the first paragraph of the notes could be used as `brief` when in `folder_brief_live`.

By paragraph, I mean paragraph that do not consist of a single image, obviously.

Cheers

**Comment by xpgo** [comment]
Thanks for the suggestion, I will implement it in the next release.

**Comment by xpgo** [comment]
now it use the  first found paragraph within notes as brief in v0.6.2.
however, to limit the length of brief, the default max length of brief is 64, if you want to change it, please use the key briefMax as described in [ccard Syntax](https://github.com/xpgo/obsidian-folder-note-plugin/blob/main/doc/ccard-syntax.md).
