### ISSUE TITLE
Unescaped quotes in brief

### ISSUE THREAD

**Issue by ngirard** [xpgo/obsidian-folder-note-plugin#4]
Folder note plugin uses the section titles of notes as brief when generating its JSON data.

When a section of a note contains a quote, the corresponding `brief` attribute contains an unescaped quote, leading to incorrect JSON contents that cannot be rendered.

**Comment by xpgo** [comment]
I didn't consider that at the begining. I will fix that in the next release, thanks.

**Comment by ngirard** [comment]
For the record: the problem also arises using v0.6.1 and when using the first paragraphs as briefs.

**Comment by xpgo** [comment]
The problem should have been fixed in v0.6.2, thanks.

**Comment by ngirard** [comment]
> The problem should have been fixed in v0.6.2

It has, thanks !

> And, to escape the quotes, we should use double quotes, '' instead of \', because it is YAML format.

I was about to close this report, but you might want to add this information to the documentation first ?

**Comment by xpgo** [comment]
solved.

**Comment by ngirard** [comment]
@xpgo, you might want to add to the documentation
* a note about the `briefMax` value;
* a paragraph explaining how to escape quotes when generating static contents by hand.

Cheers

**Comment by xpgo** [comment]
yeah, corresponding explaination have already been added to the document: https://github.com/xpgo/obsidian-folder-note-plugin/blob/main/doc/ccard-syntax.md#item-types

**Comment by ngirard** [comment]
Great, thanks !
