### ISSUE TITLE
Removing a folder doesn't remove the file, but the file stays hidden

### ISSUE THREAD

**Issue by ibestvina** [xpgo/obsidian-folder-note-plugin#6]
Obviously this only affects the "file outside folder" mode.

1. Create a folder
2. Ctrl+click to create a file.
3. Remove folder

Result: file still exists, but is hidden until Obsidian is restarted.

Expected behavior: not really sure - either to remove the file, or to show it. I guess removing it makes most sense?

**Comment by xpgo** [comment]
In v0.7.0 turn on the `Delete Folder Note` option in the settings page to enable this feature.

**Comment by ibestvina** [comment]
Great work!

**Comment by xpgo** [comment]
Try to disable and then enable the plugin, the options should appear.
make sure the folder method is selected as `Folder Name Outside`，the options is available only for outside mode.
![图片](https://user-images.githubusercontent.com/16876402/108502276-876fd180-72ed-11eb-850a-bb2259497368.png)

**Comment by ibestvina** [comment]
Works now, thank you very much!
