### ISSUE TITLE
Folder brief includes both file and folder when "file outside folder" mode is used

### ISSUE THREAD

**Issue by ibestvina** [xpgo/obsidian-folder-note-plugin#7]
As stated in the title - when file-outside-folder mode is used, the folder brief shows both the folder and the file as separate cards. I don't know if this is intentional, but it would be great to have an option to disable it so it only shows the note (if note exists of course). Additionally, if note doesn't exist, clicking on that card creates it and opens the newly created note.

**Comment by xpgo** [comment]
now with v0.7.0, it should just show the folder note alone for outside mode. 
However, clicking on a folder card to create a new folder note is not supported yet, I think it might cause unexpected behavior.

**Comment by ibestvina** [comment]
Perfect, thanks!
