### ISSUE TITLE
Auto insertion of date at the top of page?

### ISSUE THREAD

**Issue by yarub123** [xpgo/obsidian-folder-note-plugin#75]
Whether it's dataview notation or frontmatter, doesn't matter. Anyway possible of having it auto-insert the date?
For e.g.,: `date:: {{date}}` or `creation date:: {{date}}` or even just have it accept date notation like `date:: {M/dd/yy, h:mm a}`

**Comment by TheDestroyer1** [comment]
these are all possible with other plugins into obsidian or some Css snippets, but they are not goal or part of the Folder note plugin.
