### ISSUE TITLE
Multiple uses of template values do not work

### ISSUE THREAD

**Issue by ibestvina** [xpgo/obsidian-folder-note-plugin#9]
If you set this as a config template:
```
{{FOLDER_NAME}}
{{FOLDER_NAME}}
```
It only fills in the first occurrence.

I tried this because I got the idea that aliases could be used to overcome the cons of index files. If you use something like this:
````
---
aliases: [{{FOLDER_NAME}}]
---
# {{FOLDER_NAME}}

```ccard
type: folder_brief_live
imagePrefix: 'attachments/'
```
````
then linking to this would work great - Obsidian will automatically convert `[[myfolder]]` to `[[myfolder/_about_.md|myfolder]]`.

**Comment by xpgo** [comment]
you have lots of good ideas 👍 , thanks, now the v0.7.1 should have fixed the issue, try and play with it.

**Comment by ibestvina** [comment]
Thank you!
